logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
security:
  basic:
    enabled: false

spring:
  h2:
    console:
      enabled: true
      path: /h2-console